# Generated by Django 5.0.4 on 2024-07-05 05:54

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='customer',
            name='profile_image',
            field=models.ImageField(default=django.utils.timezone.now, upload_to='profileimg'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='orderstatus',
            name='status',
            field=models.CharField(choices=[('P', 'Packed'), ('D', 'Dispached'), ('A', 'Accepted'), ('R', 'Getting Ready'), ('C', 'Canceled'), ('DI', 'Delivered')], default='Pending', max_length=3),
        ),
        migrations.AlterField(
            model_name='product',
            name='category',
            field=models.CharField(choices=[('CC', 'CupCake'), ('IC', 'Icecream'), ('B', 'Burger'), ('P', 'Pizza')], max_length=2),
        ),
    ]
