# Generated by Django 5.0.4 on 2024-07-05 17:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_customer_profile_image_alter_orderstatus_status_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='customer',
            name='profile_image',
        ),
        migrations.AlterField(
            model_name='orderstatus',
            name='status',
            field=models.CharField(choices=[('A', 'Accepted'), ('R', 'Getting Ready'), ('D', 'Dispached'), ('P', 'Packed'), ('DI', 'Delivered'), ('C', 'Canceled')], default='Pending', max_length=3),
        ),
        migrations.AlterField(
            model_name='product',
            name='category',
            field=models.CharField(choices=[('IC', 'Icecream'), ('P', 'Pizza'), ('B', 'Burger'), ('CC', 'CupCake')], max_length=2),
        ),
    ]
