# Generated by Django 5.0.4 on 2024-07-06 10:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0005_alter_orderstatus_status_alter_product_category'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='customer',
            name='profile_image',
        ),
        migrations.AlterField(
            model_name='orderstatus',
            name='status',
            field=models.CharField(choices=[('R', 'Getting Ready'), ('A', 'Accepted'), ('C', 'Canceled'), ('D', 'Dispached'), ('P', 'Packed'), ('DI', 'Delivered')], default='Pending', max_length=3),
        ),
        migrations.AlterField(
            model_name='product',
            name='category',
            field=models.CharField(choices=[('B', 'Burger'), ('P', 'Pizza'), ('CC', 'CupCake'), ('IC', 'Icecream')], max_length=2),
        ),
    ]
