# Generated by Django 5.0.4 on 2024-07-06 16:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0006_remove_customer_profile_image_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='orderstatus',
            name='status',
            field=models.CharField(choices=[('P', 'Packed'), ('A', 'Accepted'), ('C', 'Canceled'), ('DI', 'Delivered'), ('R', 'Getting Ready'), ('D', 'Dispached')], default='Pending', max_length=3),
        ),
        migrations.AlterField(
            model_name='product',
            name='category',
            field=models.CharField(choices=[('CC', 'CupCake'), ('IC', 'Icecream'), ('P', 'Pizza'), ('B', 'Burger')], max_length=2),
        ),
    ]
